inherit_from: .rubocop_todo.yml

require: rubocop-rails

Layout/AccessModifierIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'subject', 'expect', 'let']