inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails 
  - rubocop-rspec

Layout/AccessModifierIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false
  
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'subject', 'expect', 'let']

Layout/EndOfLine:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - spec/requests/publishers_spec.rb

Rails/FilePath:
  Enabled: false
  